[project]
name = "apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flasgger==0.9.7.1",
    "flask==2.3.3",
    "flask-cors==4.0.0",
    "psycopg[binary]>=3.2",
    "python-dotenv==1.0.0",
    "PyJWT>=2.8",
]

[tool.uv.workspace]
members = [
    "Python_app",
]
